# Overcast development container
FROM debian:10

# Update packages and install required dependencies
RUN apt-get update && \
    apt-get install -y gcc

# Set the working directory inside the container
WORKDIR /source

# Default command to run (modify as needed)
CMD ["/bin/bash"]
